### ISSUE TITLE
Report 1

### ISSUE THREAD

**Issue by MrGPalo** [MrGPalo/Tetris#2]
Este fin de semana no he podido avanzar gran cosa, únicamente he preparado los archivos que creo que voy a usar, a partir de mañana me pondré a ello, sobretodo lo que quiero hacer mañana es preparar el primer actor con el movimiento básico de caída, junto con el bucle de renderizado y los tipos para typescript.

**Comment by amargopastor** [comment]
Tienes el 100% de nuestra atención @MrGPalo . Mucho ánimo! 🚀 🚀 🚀
