### ISSUE TITLE
Pérdida de pieza

### ISSUE THREAD

**Issue by MrGPalo** [MrGPalo/Tetris#8]
**Describe the bug**
Cuando dejamos que la pieza llegue a la base del canvas y pulsamos arrowdown la pieza sale del canvas. Si lo hacemos con la barra espaciadora no sucede este bug.

**To Reproduce**
1. Cargar el archivo
2. Dejar que la pieza llegue por si misma hasta la base o ayudarla con ArrowDown, no utilizar Spacebar en ningun caso
3. Cuando llegue a la base volver a pulsar ArrowDown
4. La pieza sale del canvas

**Expected behavior**
No debería salir del canvas

**Screenshots**
![image](https://user-images.githubusercontent.com/92857877/147668377-a00762bf-ae65-443a-a674-a1c95f59f56d.png)
Así queda cuando no usamos Spacebar.
![image](https://user-images.githubusercontent.com/92857877/147668411-c6c139ff-6854-400c-a771-47ac926f0f4e.png)
Así queda cuando usamos Spacebar y debería funcionar igual para ArrowDown si esta en el límite del canvas
![image](https://user-images.githubusercontent.com/92857877/147668507-f647b89d-b6e4-40ff-9e09-83d55804eb3d.png)
Así queda despues de usar ArrowDown cuando ya esta en su "límite" con ArrowDown

**Comment by amargopastor** [comment]
@MrGPalo tu pieza se sale del canvas porque el condicional que tienes en `ArrowDown` no se cumple y permite actualizar la posición si la posición de origen y no es **exactamente** el valor que le indicas:

```ts
case `ArrowDown`:
  if (this.origin.y != 912 - this.pieceSize.h) {
    this.origin.y += this.pieceSize.w;
  }
```
La solución rápida es que `ArrowDown` debería incrementar la velocidad, no la posición. De esta manera consigues lo que quieres: que la pieza caiga más rápido pero que se sigan respetando tus límites. Te hago commit con la solución: solo tienes que ajustar la velocidad y añadir un keyboard_event_up que disminuya la velocidad.

No obstante deberías atacar el problema real y es que tienes unos límites de pixeles nada funcionales. Tu juego, a diferencia del de la mayoría de tus compañeros, debe ser una cuadrícula bien medida donde una variable debería contener el alto del canvas y dividir este valor en el número de rows que quieras disponer en tu tetris. Cada row debería ser la altura de tu pieza cuadrado, por ejemplo. Siempre que puedas trabaja con variables, no números dispersos a lo largo de tu file.

Tienes un 912 calculado a ojo de buen cubero (que debería ser un parámetro del actor, por ejemplo, un tileSize) que va a hacer que te pelees mucho tiempo con cada pequeño arreglo o pieza nueva que introduzcas. Genera un canvas inicial que quepa en un alto medio de monitor (que yo tengo una buena pantalla en casa y aún así tengo que hacer scroll para jugar a tu juego) y divide entre en el número de casillas que quieras tener en total. Tu GameSpace puede ser igual de alto y simplemente acotar los laterales.

**Comment by MrGPalo** [comment]
De acuerdo, voy a crear la plantilla con las medidas de las diversas zonas del canvas.
